services:
  - type: web
    name: menu-backend
    env: node
    region: singapore
    plan: free
    buildCommand: yarn install && node force-postgresql.js && rm -rf node_modules/.prisma node_modules/@prisma/client && npx prisma generate && npx prisma migrate deploy && yarn build
    startCommand: node dist/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /
